name: MSG Action

# Este workflow executa a MeasureSoftGram Action, que analisa o projeto e comenta uma tabela de métricas nos Pull Requests.

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "develop", "main" ]

jobs:
  msgram_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: MeasureSoftGram Action
        uses: fga-eps-mds/MeasureSoftGram-Action@main # NOSONAR
        continue-on-error: true
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          msgramServiceToken: ${{ secrets.MSGRAM_SERVICE_TOKEN }}
          productName: "MeasureSoftGram"
          workflowName: "Rodar Testes"
          collectSonarqubeMetrics: "true"
          collectGithubMetrics: "true"
