name: Rodar Testes

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"

      - name: Instalar uv
        uses: astral-sh/setup-uv@1edb52594c857e2b5b13128931090f0640537287 # v5.3.0

      - name: Instalar dependências
        run: uv sync --frozen --no-install-project --all-extras

      - name: Rodar Linter (flake8)
        run: |
          uvx --no-build flake8==7.1.1 src/

      - name: Rodar testes
        run: |
          uv run --locked coverage erase
          uv run --locked coverage run -m pytest src -vv --junitxml=./junit.xml
          uv run --locked coverage xml -o coverage.xml
          uv run --locked coverage report --show-missing

      - name: Rodar Migrations
        run: |
          uv run --locked python src/manage.py migrate
          uv run --locked python src/manage.py makemigrations --check --dry-run

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
